==== Соглашение

В данной спецификации устанавливает следюущие роли и обязаности:

* разработчик приложения, тот кто использует CDI сервисы и
* поставщики, тот кто реализует функционал опредленный в этой спецификации, а так же предоставляет среду выполнения
в которой выполняется приложение.

Эта среда выполнения называется контейнер. Например, контейнер это может быть контейнер Java EE, либо же встраиваемый
EJB контейнер.

Принципы, программная модель, наследование и специализация, связывание интерцепторов, декорация bean'ов, и
методы наблюдение (не забыть ссылки на главы) опредляют: модель программирования для Java EE компонентов,
использующих приемущества сервисов данной спецификации; обязанности разработчика компонентов и аннотации используемые
разработчиком для описания метаданных.

Внедрение и поиск зависимостей, пространства и контексты, жизненный цикл контекстных экземпляров, декораторы,
события и интерцепторы (ссылки на главы) определяют семантику и поведение сервисов, ответсвенность за реализацию
контейнера и API используемые приложением для прямого взаимодействия с контейнером.

Упаковка и развертывание определяет (ссылка на главу): каким образов Java EE приложения, использующие CDI сервисы,
должны быть упакованы внутрь бин-архивов и отвественность реализованного контейнера вовремя инициализировать приложение.

Портативные расширения, контекстно-зависимый интерфейс и контекстный интерфейс (ссылка на главы) определяет
SPI.footnoteref:1[] что позволяет интегрировать портативные расширения с контейнером.