=== Глава 1. Архитектура

Эта спецификация определяет мощный набор дополнительных сервисов, помогающих улучшить структуру кода приложения.

. четко определенный жизненный цикл с отслеживанием состояний объектов, связанных с жизненным циклом контекстов,
где множество контекстов расширяемое;
. сложный, типизированный механизм внедрения зависимостей, включающий возможность внедрения на этапе сборки или
развертывания, без подробной конфигурации;
. поддержка модульности JavaEE и ее архитектурных компонент - модульная структура Java EE приложений учитывается
при разрешении зависимостей между компонентами;
. интеграция с единым языком выражение (EL), позволяющая использовать любой контекстуальный объект прямо внутри
JSF или JSP страниц;
. возможность декорирования внедряемых объектов
. возможность ассоциирование интерцепторов с объектами, с помощью типизированного _связывания интерцептеров_;
. модель уведомлений о событии;
. дополнительный контекст web-диалог, к трем контекстам спецификации Java сервлетов;
. SPI.footnote:[интерфейс поставщика услуг] позволяющий аккуратно интегрировать портативные расширения с контейнером.

Сервисы определенные в данной спецификации позволяют объектам быть связанными с жизненным циклом контекстов, внедренными,
ассоциироваться с перехватчиками и декораторами и взаимодействовать в слабосвязанной форме с помощью событийной модели.
Разные виды объектов являются внедряемыми, включая сессионные компоненты EJB3, компоненты управления и Java EE ресурсы.
Эти объекты называются - bean'ами, а экземпляры bean'ов, принадлежащие контекстам, - контекстные экземпляры.
Такие экземпляры могут быть внедрены в другие объекты сервисом внедрения зависимостей.

Чтобы воспользоваться этими преимуществами, разработчик предоставляет дополнительные метаданные bean-уровня в виде
Java аннотаций, а на уровне приложения в виде XML-дескриптора.

Использование этих сервисов существенно упрощает задачу создания Java EE приложений, интеграции Java EE web-уровня с
Java EE энтерпрайз сервисами. В частности, EJB компоненты могут быть использованы как управляемые компоненты JSF,
таким образом интегрируя программные модели из EJB и JSF.

Даже возможна интеграция с другими фреймворками. Портативные расширения могут предоставлять объекты для внедрения или
получения контекстных экземпляров используя сервис внедрения зависимостей. Фреймворк даже может вызывать и наблюдать
за событиями используя сервис уведомлений о событиях.

Приложение использующие преимущество этих сервисов может быть разработано на среде Java EE или Java SE. Если приложение
использует сервисы Java EE такие, как менеджер транзакций и persistence.footnote:[JPA] в среде Java SE, то сервис обычно
ограничиваются, подмножеством определенным для встроенного использования EJB спецификацией.

include::contracts.adoc[]

include::relationship.adoc[]

include::introductory.adoc[]
