==== Связь с другими спецификациями

Разработчик приложения создает компоненты, управляемые контейнером, такие как
JavaBeans, EJBs или сервлеты и предоставляет дополнительные метаданные,
описывающие дополнительное поведение определенное этой спецификации.

Эти компоненты могут извлечь выгоду из сервисов определенной в данной спецификации,
вместе с корпоративными и презентационными аспектами определенными другими
технологиями Java EE.

В дополнении, эта спецификация определяет SPI, позволяющий использовать альтернативы,
не платформенные технологии для интеграции с контейнером и средой Java EE, например,
альтернативные web-презентационные технологии.

===== Отношение к спецификации платформы Java EE

В окружении Java EE все _классы имеющие, внедряемые компоненты_, как описано в
спецификации платформы Java EE, могут внедрять их через службу внедрения зависимостей.

Спецификация платформы Java EE определяет средство для внедрения ресурсов, которые
существуют в её среде компонентов. Ресурсы идентифицируются строковыми именами.
Эта спецификация усиливает данную функциональность, добавляя возможность
внедрять неограниченные наборы типов, объектов, в том числе компонентные ресурсы среды,
на основе квалификаторов, но не ограничиваясь ими.

===== Отношения к EJB.

EJB определяет программную модель для компонентов приложения, которые обращаются к
транзакционным ресурсам в многопользовательской среде. EJB позволяет декларативно,
с помощью аннотаций и дескрипторов развертывания XML, описывать такие проблемы,
как доступность к ресурсу основе ролей, разграничение транзакций, параллелизм и масштабируемость,
а так же принудительное выполнение EJB контейнером.

EJB компоненты могут сохранять свое состояние, но не быь контекстуальными по природе своей.
Ссылки на такие компоненты, должны явно передаваться между клиентами, а сами экземпляры этих
компонентов должны быть явно уничтожены приложением.

Эта спецификация расширяет компонентную модель EJB за счет контекстного управления жизненным циклом.

Любой сессионный компонент, экземпляр которого, полученный с помощью службы внедрения зависимостей,
является контекстным экземпляром. Он привязан к контексту жизненного цикла и доступен для других объектов,
которые выполняются в этом контексте. Контейнер автоматически создает экземпляр, когда он нужен клиенту.
Когда контекст заканчивается, контейнер автоматически уничтожает экземпляр.

Message-driven и сущности, по своей природе, не являются контекстными объектами, поэтому
не могут быть внедрены в контекстные объекты.

Контейнер выполняет внедрение зависимостей для всех экземпляров компонента, сессий и message-driven,
даже тех, которые не являются контекстными экземплярами.

===== Отношение к управляемым компонентам

Спецификация управляемых компонентов определяет базовую модель программирования для компонентов приложения, управляемых контейнером Java EE.

В этой спецификации определено, что управляемыми компонентами являются большинство классов Java, включая все компоненты JavaBeans.

В этой спецификации определено, что контекстное управление жизненным циклом и внедрение зависимостей являются общими сервисами
и применимые ко всем Managed Beans.

Любой экземпляр управляемого компонента, полученный через службу внедрения зависимостей, является контекстным экземпляром.
Он привязан к контексту жизненного цикла и доступен для других объектов, которые выполняются в этом контексте.
Контейнер автоматически создает экземпляр, когда он нужен клиенту. Когда контекст заканчивается,
контейнер автоматически уничтожает экземпляр.

Контейнер выполняет внедрение зависимостей для всех экземпляров управляемого компонента, даже тех,
которые не являются контекстными экземплярами.

===== Отношение к внедрению зависимостей для Java

Спецификация Внедрения зависимостей для Java определяет набор аннотаций для объявления внедряемых полей,
методов и конструкторов bean-компонента. Сервис внедрения зависимостей использует эти аннотации.

===== Отношение к перехватчикам Java

Спецификация перехватчикам Java определяет базовую модель программирования и семантику для перехватчиков.
Эта спецификация расширяет эту модель, предоставляя возможность связывать перехватчики с bean-компонентами,
используя безопасные привязки перехватчиков.

===== Отношение к JSF

Java Server Faces - это фреймворк представления веб-уровня, который обеспечивает использование компонентной модели
в графическом пользовательском интерфейсе. И предоставляет модель для связи, через управляемые события,
компонентов пользовательского интерфейса с объектами, доступными через единый язык запросов (EL).

===== Отношение к валидации компонентов.

Валидация компонентов обеспечивает унифицированный способ объявления и определения ограничений для объектной модели,
определяет механизм выполнения валидации объектов и предоставляет методы валидации.

Спецификация валидации компонентов определяет компоненты для управления компонентами валидации,
включая `Validator` и `ValidatorFactory`. Ряд управляемых экземпляров компонентов валидации, включая `ConstraintValidator`,
могут использовать преимущества внедрения зависимостей. Компоненты валидации также обеспечивает поддержку проверки
параметров метода для любого bean-компонента.